export { default as Header } from './Layout//Header/header.svelte';
export { default as Menu } from './Layout/Menu/menu.svelte';
export { default as RenderCode } from './RenderCode/render.svelte';
export { default as Layout } from './Layout/layout.svelte';
export { default as ButtonDefaultTable } from './Tables/buttonDefault.svelte';
export { default as ButtonCustomTable } from './Tables/buttonCustom.svelte';
export { default as DispatchTable } from './Tables/dispatch.svelte';
export {default as ModalTable} from './Tables/modal.svelte';
export { default as UserMenuTable } from './Tables/userMenu.svelte';
export { sections } from './Layout/Menu/sections.js';
